### ISSUE TITLE
Are you sure this is running asynchronously?

### ISSUE THREAD

**Issue by kootenpv** [biesnecker/hachiko#2]
Since the watchdog code shows no sign of being async... 

What I mean is.... let's say the code in watchdog original code has a `time.sleep(10)`, then it would stall the rest of the app? Only `asyncio.sleep(10)` would work. 

So then I wonder what the benefit is of running this with asyncio :) The events are happening really fast, so there seems no point for it to be async? I really hope you have an answer, I'm trying to learn.

**Comment by adrienverge** [comment]
It's been more than a year but...

The point of this library is simply that it is asyncio-compatible. I don't know whether it's really acting async internally, but at least you can call it from an async program (it was not the case with `watchdog`).

**Comment by biesnecker** [comment]
The observer runs on a background thread, and receives updates from the OS. When it receives those updates, it runs your handler in that thread. You're right that, from the perspective of the background thread, it's not async -- it's all happening synchronously in that thread.

Essentially what this library does is give you a way to run an asynchronous callback in your main thread (or any thread you want, just not the Watchdog background thread) in response to events that occur in that background thread. That's what the `self._loop.call_soon_threadsafe()` call on line 44 is doing -- that code is running on the background thread, but the callback will run on whatever thread the loop is executing on. 

Sorry for the incredibly slow response, I hope this makes sense.
